// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFTx7E6ez7Hp_aTVRyEkz91NUIggu92U',
    appId: '1:373267461502:web:4cda0a1359890dec5fef2f',
    messagingSenderId: '373267461502',
    projectId: 'flutterfirenotes-e55aa',
    authDomain: 'flutterfirenotes-e55aa.firebaseapp.com',
    storageBucket: 'flutterfirenotes-e55aa.appspot.com',
    measurementId: 'G-TJ18WPLKZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBot1hr8hTxrXyhMqR84H_TOdanwaYmAoc',
    appId: '1:373267461502:android:c9bd2c0a790974cf5fef2f',
    messagingSenderId: '373267461502',
    projectId: 'flutterfirenotes-e55aa',
    storageBucket: 'flutterfirenotes-e55aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6eX4bv0nOXfE1XRy4uXL_t3k4vNMSLxk',
    appId: '1:373267461502:ios:f9a2f048c04a219e5fef2f',
    messagingSenderId: '373267461502',
    projectId: 'flutterfirenotes-e55aa',
    storageBucket: 'flutterfirenotes-e55aa.appspot.com',
    iosBundleId: 'com.example.getxstatePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6eX4bv0nOXfE1XRy4uXL_t3k4vNMSLxk',
    appId: '1:373267461502:ios:fde85e38d15fdb155fef2f',
    messagingSenderId: '373267461502',
    projectId: 'flutterfirenotes-e55aa',
    storageBucket: 'flutterfirenotes-e55aa.appspot.com',
    iosBundleId: 'com.example.getxstatePractice.RunnerTests',
  );
}
